{
    "n_steps": 0,
    "cum_reward": 0,
    "cum_raw_reward": 0,
    "err_msg": "Exception uncaught by agent or environment in task webmall.Webmall_Find_Specific_Product_Task6.\nError:\nPage.goto: net::ERR_CONNECTION_TIMED_OUT at https://webmall-0.informatik.uni-mannheim.de/\nCall log:\nnavigating to \"https://webmall-0.informatik.uni-mannheim.de/\", waiting until \"load\"\n",
    "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\lenna\\WebMall-Efficent\\Browsergym\\browsergym\\experiments\\src\\browsergym\\experiments\\loop.py\", line 410, in run\n    step_info.from_reset(\n  File \"C:\\Users\\lenna\\WebMall-Efficent\\Browsergym\\browsergym\\experiments\\src\\browsergym\\experiments\\loop.py\", line 215, in from_reset\n    self.obs, env_info = env.reset(seed=seed)\n                         ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\gymnasium\\wrappers\\common.py\", line 146, in reset\n    return super().reset(seed=seed, options=options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\gymnasium\\core.py\", line 333, in reset\n    return self.env.reset(seed=seed, options=options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\gymnasium\\wrappers\\common.py\", line 400, in reset\n    return super().reset(seed=seed, options=options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\gymnasium\\core.py\", line 333, in reset\n    return self.env.reset(seed=seed, options=options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\WebMall-Efficent\\Browsergym\\browsergym\\core\\src\\browsergym\\core\\env.py\", line 339, in reset\n    task_goal, task_info = self.task.setup(page=self.page)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\WebMall-Efficent\\Browsergym\\browsergym\\webmall\\src\\browsergym\\webmall\\task.py\", line 91, in setup\n    page.goto(start_url, timeout=50000)\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 8686, in goto\n    self._sync(\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 519, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lenna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_TIMED_OUT at https://webmall-0.informatik.uni-mannheim.de/\nCall log:\nnavigating to \"https://webmall-0.informatik.uni-mannheim.de/\", waiting until \"load\"\n\n",
    "stats.cum_steps": 1,
    "terminated": null,
    "truncated": null
}